name: CI & CD

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build_and_push_image:
    name: Build and push image
    runs-on: ubuntu-latest
    steps:
      - name: Set additional variables
        id: variables
        uses: icalia-actions/common-variables@v0.0.3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.ICALIA_DOCKER_HUB_USERNAME }}
          password: ${{ secrets.ICALIA_DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push image
        id: build_image
        uses: docker/build-push-action@v2
        with:
          push: ${{ github.ref == 'refs/heads/main' }}
          platforms: linux/amd64,linux/arm64
          tags: |
            icalialabs/chromium:${{ steps.variables.outputs.git-dasherized-branch }}
            icalialabs/chromium:93.0.4577.82
            icalialabs/chromium:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
